#!/usr/bin/env -S ucode -R
"use strict";

let fs = require("fs");

function load_json(path) {
	let fd = fs.open(path, "r");

	assert(fd, sprintf("Unable to open %s", path));

	let data = json(fd.read("all"));
	fd.close();

	assert(type(data) == "object", sprintf("Unable to parse %s", path));

	return data;
}

function print_line(line) {
	printf("%s\n", line);
}

let generator_dir = sourcepath(0, true);
let repo_dir = generator_dir + "/../..";
let schema = load_json(repo_dir + "/ucentral.schema.pretty.json");

print_line("#!/usr/bin/env bash");
print_line("set -euo pipefail");
print_line("");
print_line("if ! command -v jq >/dev/null 2>&1; then");
print_line("  echo \"jq is required to run validator/bash/schemareader.sh\" >&2");
print_line("  exit 2");
print_line("fi");
print_line("");
print_line("usage() {");
print_line("  echo \"Usage: $0 <input.json>\" >&2");
print_line("}");
print_line("");
print_line("if [ \"${1:-}\" = \"-h\" ] || [ \"${1:-}\" = \"--help\" ]; then");
print_line("  usage");
print_line("  exit 0");
print_line("fi");
print_line("");
print_line("if [ \"$#\" -gt 1 ]; then");
print_line("  usage");
print_line("  exit 2");
print_line("fi");
print_line("");
print_line("input_file=${1:-}");
print_line("cleanup_input=0");
print_line("");
print_line("if [ -z \"$input_file\" ]; then");
print_line("  input_file=$(mktemp)");
print_line("  cleanup_input=1");
print_line("  cat > \"$input_file\"");
print_line("elif [ ! -f \"$input_file\" ]; then");
print_line("  echo \"Input file not found: $input_file\" >&2");
print_line("  exit 2");
print_line("fi");
print_line("");
print_line("schema_file=$(mktemp)");
print_line("jq_program=$(mktemp)");
print_line("cleanup() {");
print_line("  rm -f \"$schema_file\" \"$jq_program\"");
print_line("  if [ \"$cleanup_input\" -eq 1 ]; then");
print_line("    rm -f \"$input_file\"");
print_line("  fi");
print_line("}");
print_line("trap cleanup EXIT");
print_line("");
print_line("cat > \"$schema_file\" <<'__SCHEMA__'");
printf("%.J\n", schema);
print_line("__SCHEMA__");
print_line("");
print_line("cat > \"$jq_program\" <<'__JQ__'");
print_line("def run($root; $input):");
print_line("  def validate($root; $schema; $value; $path):");
print_line("    def variant_passes($root; $variant; $value; $path):");
print_line("      (validate($root; $variant; $value; $path) | length) == 0;");
print_line("");
print_line("def ptr_unescape:");
print_line("  gsub(\"~1\"; \"/\") | gsub(\"~0\"; \"~\");");
print_line("");
print_line("def ptr_escape:");
print_line("  gsub(\"~\"; \"~0\") | gsub(\"/\"; \"~1\");");
print_line("");
print_line("def child_path($path; $segment):");
print_line("  if $path == \"\" then");
print_line("    \"/\" + (($segment | tostring) | ptr_escape)");
print_line("  else");
print_line("    $path + \"/\" + (($segment | tostring) | ptr_escape)");
print_line("  end;");
print_line("");
print_line("def prepare_key($key):");
print_line("  (($key | tostring) | gsub(\"[^A-Za-z0-9_]+\"; \"_\"))");
print_line("  | if test(\"^[0-9]\") then \"_\" + . else . end;");
print_line("");
print_line("def schema_type($value):");
print_line("  if $value == null then \"null\"");
print_line("  elif ($value | type) == \"boolean\" then \"boolean\"");
print_line("  elif ($value | type) == \"string\" then \"string\"");
print_line("  elif ($value | type) == \"array\" then \"array\"");
print_line("  elif ($value | type) == \"object\" then \"object\"");
print_line("  elif ($value | type) == \"number\" then");
print_line("    if ($value | floor) == $value then \"integer\" else \"number\" end");
print_line("  else");
print_line("    ($value | type)");
print_line("  end;");
print_line("");
print_line("def value_matches_type($expected; $value):");
print_line("  if $expected == \"number\" then");
print_line("    ($value | type) == \"number\"");
print_line("  elif $expected == \"integer\" then");
print_line("    (($value | type) == \"number\") and (($value | floor) == $value)");
print_line("  elif $expected == \"null\" then");
print_line("    $value == null");
print_line("  else");
print_line("    schema_type($value) == $expected");
print_line("  end;");
print_line("");
print_line("def error_at($path; $message):");
print_line("  [((if $path == \"\" then \"/\" else $path end) + \": \" + $message)];");
print_line("");
print_line("def resolve_ref($root; $ref):");
print_line("  if ($ref | startswith(\"#/\")) then");
print_line("    reduce (($ref[2:] | split(\"/\"))[]) as $part ($root; .[$part | ptr_unescape])");
print_line("  else");
print_line("    null");
print_line("  end;");
print_line("");
print_line("def validate_variants($root; $schema; $value; $path):");
print_line("  (if (($schema.anyOf? | type) == \"array\") and (($schema.anyOf | length) > 0) then");
print_line("     ([ $schema.anyOf[] | variant_passes($root; .; $value; $path) ] | map(select(.)) | length) as $count |");
print_line("     if $count >= 1 then [] else error_at($path; \"must match at least one anyOf variant\") end");
print_line("   else [] end)");
print_line("  +");
print_line("  (if (($schema.oneOf? | type) == \"array\") and (($schema.oneOf | length) > 0) then");
print_line("     ([ $schema.oneOf[] | variant_passes($root; .; $value; $path) ] | map(select(.)) | length) as $count |");
print_line("     if $count == 1 then [] else error_at($path; \"must match exactly one oneOf variant\") end");
print_line("   else [] end)");
print_line("  +");
print_line("  (if (($schema.allOf? | type) == \"array\") and (($schema.allOf | length) > 0) then");
print_line("     (([ $schema.allOf[] | validate($root; .; $value; $path) ] | add) // [])");
print_line("   else [] end);");
print_line("");
print_line("def validate_object($root; $schema; $value; $path):");
print_line("  if ($value | type) != \"object\" then");
print_line("    []");
print_line("  else");
print_line("    (if (($schema.required? | type) == \"array\") then");
print_line("       [ $schema.required[] as $req | select($value | has($req) | not) |");
print_line("         ((child_path($path; $req)) + \": is required\") ]");
print_line("     else [] end)");
print_line("    +");
print_line("    (if $schema.additionalProperties? == false then");
print_line("       (($schema.properties? // {}) as $props |");
print_line("       [ ($value | keys_unsorted[]) as $key");
print_line("         | select($props | has($key) | not)");
print_line("         | ((child_path($path; $key)) + \": additional property is not allowed\") ]");
print_line("       )");
print_line("     else [] end)");
print_line("    +");
print_line("    ((($schema.properties? // {}) as $props");
print_line("      | [ ($props | to_entries[]) as $entry");
print_line("          | select($value | has($entry.key))");
print_line("          | validate($root; $entry.value; $value[$entry.key]; child_path($path; $entry.key)) ]");
print_line("      | add) // [])");
print_line("    +");
print_line("    (if (($schema.minProperties? | type) == \"number\") and (($value | length) < $schema.minProperties) then");
print_line("       error_at($path; \"must contain at least \\($schema.minProperties) properties\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.maxProperties? | type) == \"number\") and (($value | length) > $schema.maxProperties) then");
print_line("       error_at($path; \"must contain at most \\($schema.maxProperties) properties\")");
print_line("     else [] end)");
print_line("  end;");
print_line("");
print_line("def validate_array($root; $schema; $value; $path):");
print_line("  if ($value | type) != \"array\" then");
print_line("    []");
print_line("  else");
print_line("    (if (($schema.minItems? | type) == \"number\") and (($value | length) < $schema.minItems) then");
print_line("       error_at($path; \"must contain at least \\($schema.minItems) items\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.maxItems? | type) == \"number\") and (($value | length) > $schema.maxItems) then");
print_line("       error_at($path; \"must contain at most \\($schema.maxItems) items\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if ($schema.items? | type) == \"object\" then");
print_line("       (([ range(0; $value | length) as $idx");
print_line("         | validate($root; $schema.items; $value[$idx]; child_path($path; $idx)) ]");
print_line("         | add) // [])");
print_line("     else [] end)");
print_line("  end;");
print_line("");
print_line("def validate_string($schema; $value; $path):");
print_line("  if ($value | type) != \"string\" then");
print_line("    []");
print_line("  else");
print_line("    (if (($schema.minLength? | type) == \"number\") and (($value | length) < $schema.minLength) then");
print_line("       error_at($path; \"must have length >= \\($schema.minLength)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.maxLength? | type) == \"number\") and (($value | length) > $schema.maxLength) then");
print_line("       error_at($path; \"must have length <= \\($schema.maxLength)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.pattern? | type) == \"string\") and (($value | test($schema.pattern)) | not) then");
print_line("       error_at($path; \"must match pattern \\($schema.pattern)\")");
print_line("     else [] end)");
print_line("  end;");
print_line("");
print_line("def validate_number($schema; $value; $path):");
print_line("  if ($value | type) != \"number\" then");
print_line("    []");
print_line("  else");
print_line("    (if (($schema.minimum? | type) == \"number\") and ($value < $schema.minimum) then");
print_line("       error_at($path; \"must be >= \\($schema.minimum)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.maximum? | type) == \"number\") and ($value > $schema.maximum) then");
print_line("       error_at($path; \"must be <= \\($schema.maximum)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.exclusiveMinimum? | type) == \"number\") and ($value <= $schema.exclusiveMinimum) then");
print_line("       error_at($path; \"must be > \\($schema.exclusiveMinimum)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.exclusiveMaximum? | type) == \"number\") and ($value >= $schema.exclusiveMaximum) then");
print_line("       error_at($path; \"must be < \\($schema.exclusiveMaximum)\")");
print_line("     else [] end)");
print_line("    +");
print_line("    (if (($schema.multipleOf? | type) == \"number\") and (($value / $schema.multipleOf | floor) * $schema.multipleOf != $value) then");
print_line("       error_at($path; \"must be a multiple of \\($schema.multipleOf)\")");
print_line("     else [] end)");
print_line("  end;");
print_line("");
print_line("def validate_type($schema; $value; $path):");
print_line("  if ($schema.type? | type) == \"string\" then");
print_line("    if value_matches_type($schema.type; $value) then []");
print_line("    else error_at($path; \"must be of type \\($schema.type), got \\(schema_type($value))\") end");
print_line("  elif ($schema.type? | type) == \"array\" then");
print_line("    if [ $schema.type[] | value_matches_type(.; $value) ] | any then []");
print_line("    else error_at($path; \"must match one of types \\(($schema.type | join(\", \")))\") end");
print_line("  else [] end;");
print_line("");
print_line("def validate_constraints($root; $schema; $value; $path):");
print_line("  validate_variants($root; $schema; $value; $path)");
print_line("  + validate_type($schema; $value; $path)");
print_line("  + (if ($schema | has(\"const\")) and $value != $schema.const then");
print_line("       error_at($path; \"must equal declared const value\")");
print_line("     else [] end)");
print_line("  + (if (($schema.enum? | type) == \"array\") and (($schema.enum | index($value)) == null) then");
print_line("       error_at($path; \"must be one of enum values\")");
print_line("     else [] end)");
print_line("  + validate_string($schema; $value; $path)");
print_line("  + validate_number($schema; $value; $path)");
print_line("  + validate_array($root; $schema; $value; $path)");
print_line("  + validate_object($root; $schema; $value; $path);");
print_line("");
print_line("def prepare($root; $schema; $value):");
print_line("  def prepare_variant($variant):");
print_line("    prepare($root; $variant; $value);");
print_line("  if ($schema | type) != \"object\" then");
print_line("    $value");
print_line("  elif ($schema[\"$ref\"]? | type) == \"string\" then");
print_line("    (resolve_ref($root; $schema[\"$ref\"]) // {}) as $resolved");
print_line("    | prepare($root; ($resolved + ($schema | del(.[\"$ref\"]))); $value)");
print_line("  elif (($schema.anyOf? | type) == \"array\") and (($schema.anyOf | length) > 0) then");
print_line("    [ $schema.anyOf[] | select(variant_passes($root; .; $value; \"\")) | prepare_variant(.) ] as $prepared");
print_line("    | if ($prepared | length) == 0 then $value");
print_line("      else reduce $prepared[] as $item (null;");
print_line("        if . == null then $item");
print_line("        elif (type == \"object\") and (($item | type) == \"object\") then . + $item");
print_line("        else $item end)");
print_line("      end");
print_line("  elif (($schema.oneOf? | type) == \"array\") and (($schema.oneOf | length) > 0) then");
print_line("    [ $schema.oneOf[] | select(variant_passes($root; .; $value; \"\")) | prepare_variant(.) ] as $prepared");
print_line("    | if ($prepared | length) == 1 then $prepared[0] else $value end");
print_line("  elif (($schema.allOf? | type) == \"array\") and (($schema.allOf | length) > 0) then");
print_line("    [ $schema.allOf[] | prepare_variant(.) ] as $prepared");
print_line("    | reduce $prepared[] as $item (null;");
print_line("        if . == null then $item");
print_line("        elif (type == \"object\") and (($item | type) == \"object\") then . + $item");
print_line("        else $item end)");
print_line("  elif ($schema.type? == \"object\") or (($schema.properties? | type) == \"object\") then");
print_line("    (if ($schema.additionalProperties? == true) then $value else {} end) as $base");
print_line("    | (($schema.properties? // {}) | to_entries) as $entries");
print_line("    | reduce $entries[] as $entry ($base;");
print_line("        if ($value | has($entry.key)) then");
print_line("          .[prepare_key($entry.key)] = prepare($root; $entry.value; $value[$entry.key])");
print_line("        elif ($entry.value | has(\"default\")) then");
print_line("          .[prepare_key($entry.key)] = $entry.value.default");
print_line("        else");
print_line("          .");
print_line("        end)");
print_line("  elif ($schema.type? == \"array\") and (($schema.items? | type) == \"object\") then");
print_line("    [ $value[] | prepare($root; $schema.items; .) ]");
print_line("  else");
print_line("    $value");
print_line("  end;");
print_line("");
print_line("  if ($schema | type) != \"object\" then");
print_line("    []");
print_line("  elif ($schema[\"$ref\"]? | type) == \"string\" then");
print_line("    (resolve_ref($root; $schema[\"$ref\"]) // {}) as $resolved");
print_line("    | validate($root; ($resolved + ($schema | del(.[\"$ref\"]))); $value; $path)");
print_line("  else");
print_line("    validate_constraints($root; $schema; $value; $path)");
print_line("  end;");
print_line("");
print_line("  def prepare($root; $schema; $value):");
print_line("    def ptr_unescape:");
print_line("      gsub(\"~1\"; \"/\") | gsub(\"~0\"; \"~\");");
print_line("    def prepare_key($key):");
print_line("      (($key | tostring) | gsub(\"[^A-Za-z0-9_]+\"; \"_\"))");
print_line("      | if test(\"^[0-9]\") then \"_\" + . else . end;");
print_line("    def resolve_ref($root; $ref):");
print_line("      if ($ref | startswith(\"#/\")) then");
print_line("        reduce (($ref[2:] | split(\"/\"))[]) as $part ($root; .[$part | ptr_unescape])");
print_line("      else");
print_line("        null");
print_line("      end;");
print_line("    def prepare_variant($variant):");
print_line("      prepare($root; $variant; $value);");
print_line("    if ($schema | type) != \"object\" then");
print_line("      $value");
print_line("    elif ($schema[\"$ref\"]? | type) == \"string\" then");
print_line("      (resolve_ref($root; $schema[\"$ref\"]) // {}) as $resolved");
print_line("      | prepare($root; ($resolved + ($schema | del(.[\"$ref\"]))); $value)");
print_line("    elif (($schema.anyOf? | type) == \"array\") and (($schema.anyOf | length) > 0) then");
print_line("      [ $schema.anyOf[] | select((validate($root; .; $value; \"\") | length) == 0) | prepare_variant(.) ] as $prepared");
print_line("      | if ($prepared | length) == 0 then $value");
print_line("        else reduce $prepared[] as $item (null;");
print_line("          if . == null then $item");
print_line("          elif (type == \"object\") and (($item | type) == \"object\") then . + $item");
print_line("          else $item end)");
print_line("        end");
print_line("    elif (($schema.oneOf? | type) == \"array\") and (($schema.oneOf | length) > 0) then");
print_line("      [ $schema.oneOf[] | select((validate($root; .; $value; \"\") | length) == 0) | prepare_variant(.) ] as $prepared");
print_line("      | if ($prepared | length) == 1 then $prepared[0] else $value end");
print_line("    elif (($schema.allOf? | type) == \"array\") and (($schema.allOf | length) > 0) then");
print_line("      [ $schema.allOf[] | prepare_variant(.) ] as $prepared");
print_line("      | reduce $prepared[] as $item (null;");
print_line("          if . == null then $item");
print_line("          elif (type == \"object\") and (($item | type) == \"object\") then . + $item");
print_line("          else $item end)");
print_line("    elif ($schema.type? == \"object\") or (($schema.properties? | type) == \"object\") then");
print_line("      (if ($schema.additionalProperties? == true) then $value else {} end) as $base");
print_line("      | (($schema.properties? // {}) | to_entries) as $entries");
print_line("      | reduce $entries[] as $entry ($base;");
print_line("          if ($value | has($entry.key)) then");
print_line("            .[prepare_key($entry.key)] = prepare($root; $entry.value; $value[$entry.key])");
print_line("          elif ($entry.value | has(\"default\")) then");
print_line("            .[prepare_key($entry.key)] = $entry.value.default");
print_line("          else");
print_line("            .");
print_line("          end)");
print_line("    elif ($schema.type? == \"array\") and (($schema.items? | type) == \"object\") then");
print_line("      [ $value[] | prepare($root; $schema.items; .) ]");
print_line("    else");
print_line("      $value");
print_line("    end;");
print_line("");
print_line("  (validate($root; $root; $input; \"\")) as $errors");
print_line("  | { errors: $errors, value: (if ($errors | length) == 0 then prepare($root; $root; $input) else null end) };");
print_line("");
print_line("($schema[0]) as $root");
print_line("| ($data[0]) as $input");
print_line("| run($root; $input)");
print_line("__JQ__");
print_line("");
print_line("if ! jq -e . \"$input_file\" >/dev/null 2>&1; then");
print_line("  echo \"Invalid JSON input: $input_file\" >&2");
print_line("  exit 1");
print_line("fi");
print_line("");
print_line("result=$(jq -c -n --slurpfile data \"$input_file\" --slurpfile schema \"$schema_file\" -f \"$jq_program\")");
print_line("errors=$(printf '%s' \"$result\" | jq -r '.errors[]?')");
print_line("");
print_line("if [ -n \"$errors\" ]; then");
print_line("  printf '%s\\n' \"$errors\" >&2");
print_line("  exit 1");
print_line("fi");
print_line("");
print_line("printf '%s' \"$result\" | jq '.value'");
